### ISSUE TITLE
Million lint build error when configuring using webpack (TypeError: Cannot read properties of undefined (reading 'anya'))

### ISSUE THREAD

**Issue by uriklar** [aidenybai/million#1037]
### What version of `million` are you using?

1.0.0
### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

**Update:** - Seeing same error with rspack

In my webpack (v.5.91.0) config I added:
```
import million from '@million/lint';
plugins: [
     million.webpack(),
     ... other plugins
    ]
   ```
   
   And i'm getting this error:
   ```
  /Users/uriklar/Code/MY_PROJECT/node_modules/unplugin/dist/webpack/loaders/transform.js:104
  const plugin = (_a = this._compiler) == null ? void 0 : _a.$unpluginContext[unpluginName];
                                                                             ^

TypeError: Cannot read properties of undefined (reading 'anya')
    at Object.transform (/Users/uriklar/Code/MY_PROJECT/node_modules/unplugin/dist/webpack/loaders/transform.js:104:78)
    at LOADER_EXECUTION (/Users/uriklar/Code/MY_PROJECT/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/uriklar/Code/MY_PROJECT/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/uriklar/Code/MY_PROJECT/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /Users/uriklar/Code/MY_PROJECT/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
    ```

### What's the expected result?

The build to pass

### Link to Minimal Reproducible Example

https://stackblitz.com/sorry-cant-create-one-right-now

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ganapativs** [comment]
Same issue here. Please look into this.

```
/Users/user/project/node_modules/.pnpm/unplugin@1.10.1/node_modules/unplugin/dist/webpack/loaders/transform.js:105

  if (typeof this.query === "string") {
    console.log(this.query); // ?unpluginName=anya
    const query = new URLSearchParams(this.query);
    unpluginName = query.get("unpluginName");
  } else {
    unpluginName = this.query.unpluginName;
  }
  const plugin = (_a = this._compiler) == null ? void 0 : _a.$unpluginContext[unpluginName];
```

**Comment by grushetsky** [comment]
I have encountered the same problem.

**Comment by uriklar** [comment]
Any news on this one? Thanks

**Comment by patik** [comment]
I'm also having this issue in my Next 14 app. It often happens with memoized components that have a custom equality function (`arePropsEqual`). It seems that `arePropsEqual` does not always receive the previous and next props.

**Comment by aidenybai** [comment]
@patik taking a look!

**Comment by uriklar** [comment]
Any updates? 🙏

**Comment by wjljack** [comment]
Any updates? 🙏

**Comment by mazkaaa** [comment]
any updates? @aidenybai

**Comment by Stephcraft** [comment]
Me too
```
const plugin = (_a = this._compiler) == null ? void 0 : _a.$unpluginContext[unpluginName];
                                                                             ^
TypeError: Cannot read properties of undefined (reading 'anya')
    at Object.transform (node_modules\unplugin\dist\webpack\loaders\transform.js:111:78)
    at LOADER_EXECUTION (node_modules\loader-runner\lib\LoaderRunner.js:132:14)
    at runSyncOrAsync (node_modules\loader-runner\lib\LoaderRunner.js:133:4)
    at iterateNormalLoaders (node_modules\loader-runner\lib\LoaderRunner.js:251:2)
    at node_modules\loader-runner\lib\LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```
