### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by ylnsnv** [aidenybai/million#1048]
### What version of `million` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn,pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Tried on multiple different projects downloading million lint using pnpm/yarn/cli and it just couldn't succeed..
` ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In ../..: "@million/install@workspace:^" is in the dependencies but no package named "@million/install" is present in the workspace`

### What's the expected result?

For the installation to succeed

### Link to Minimal Reproducible Example

None

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by andrewpap22** [comment]
Same here 

`pnpm version: 9.1.4` 

After pnpm add @million/list@latest results in --> ` ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@million/install@workspace:^" is in the dependencies but no package named "@million/install" is present in the workspace`

**Comment by faribauc** [comment]
+1

Electron/Vite setup

NPM Log:
```
0 verbose cli /home/<user>/.nvm/versions/node/v21.7.1/bin/node /home/<user>/.nvm/versions/node/v21.7.1/bin/npm
1 info using npm@10.5.0
2 info using node@v21.7.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/<user>/<path>/<project>/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/<user>/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/<user>/.nvm/versions/node/v21.7.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install @million/lint
22 verbose argv "install" "@million/lint"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/<user>/.npm/_logs/2024-05-30T13_13_05_507Z-
26 verbose logfile /home/<user>/.npm/_logs/2024-05-30T13_13_05_507Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 19ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 320ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest @million/lint@*
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/@million%2flint 1021ms (cache miss)
40 silly placeDep ROOT @million/lint@1.0.0-rc.14 OK for: <project>@1.0.0 want: *
41 silly fetch manifest @axiomhq/js@1.0.0-rc.3
42 silly fetch manifest @babel/core@7.24.6
43 silly fetch manifest @babel/types@7.24.6
44 silly fetch manifest @hono/node-server@^1.11.1
45 timing idealTree Completed in 1357ms
46 timing command:install Completed in 1362ms
47 verbose stack Error: Unsupported URL Type "workspace:": workspace:^
47 verbose stack     at unsupportedURLType (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
47 verbose stack     at fromURL (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
47 verbose stack     at Function.resolve (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
47 verbose stack     at /home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1027:39
47 verbose stack     at run (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
47 verbose stack     at /home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
47 verbose stack     at new Promise (<anonymous>)
47 verbose stack     at callLimit (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
47 verbose stack     at #buildDepStep (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1041:11)
47 verbose stack     at async Arborist.buildIdealTree (/home/<user>/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
48 verbose cwd /home/<user>/<path>/<project>
49 verbose Linux 6.5.0-28-generic
50 verbose node v21.7.1
51 verbose npm  v10.5.0
52 error code EUNSUPPORTEDPROTOCOL
53 error Unsupported URL Type "workspace:": workspace:^
54 verbose exit 1
55 timing npm Completed in 1449ms
56 verbose unfinished npm timer reify 1717074785593
57 verbose unfinished npm timer reify:loadTrees 1717074785596
58 verbose unfinished npm timer idealTree:buildDeps 1717074785918
59 verbose unfinished npm timer idealTree:#root 1717074785918
60 verbose code 1
61 error A complete log of this run can be found in: /home/<user>/.npm/_logs/2024-05-30T13_13_05_507Z-debug-0.log

**Comment by Sty13** [comment]
Same issue here using bun

`error: workspace dependency "@million/install" not found`

**Comment by vice7770** [comment]
Yesterday was working with npm install now is throwing :
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

**Comment by dan-lee** [comment]
According to Discord this was fixed

**Comment by NisargIO** [comment]
@vice7770 @Sty13 @faribauc @andrewpap22 

Sorry about the trouble - this has been fixed!

Please try again `npx @million/lint@latest`
