### ISSUE TITLE
@hono throwing in Github Pages

### ISSUE THREAD

**Issue by charlieforward9** [aidenybai/million#1071]
### What version of `million` are you using?

1.0.0-rc.76

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac (Locally), Linux (Github Pages)

### What browser are you using?

Chrome, but NA

### Describe the Bug

The project works fine in local development, but when I go to deploy it on Github pages, this error is thrown. 

I noticed that @hono is a dependency of Million, so I will have to uninstall it until this is addressed.

```
failed to load config from /home/runner/work/NEW_HEAT/NEW_HEAT/vite.config.ts
error during build:
TypeError: Class extends value undefined is not a constructor or null
    at file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/@hono/node-server/dist/index.mjs:20:15
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadConfigFromBundledFile (file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66984:[15](https://github.com/charlieforward9/NEW_HEAT/actions/runs/9788038243/job/27025467467#step:5:16))
    at async loadConfigFromFile (file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66825:24)
    at async resolveConfig (file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66435:24)
    at async build (file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65530:[18](https://github.com/charlieforward9/NEW_HEAT/actions/runs/9788038243/job/27025467467#step:5:19))
    at async CAC.<anonymous> (file:///home/runner/work/NEW_HEAT/NEW_HEAT/node_modules/vite/dist/node/cli.js:828:5)
Error: Process completed with exit code 1.
```

### What's the expected result?

No errors, working as expected like in development

### Link to Minimal Reproducible Example

NA

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
No repro
