### ISSUE TITLE
Does Million not support Node v23?

### ISSUE THREAD

**Issue by Poolshark** [aidenybai/million#1167]
I am not 100% certain, but either since I have updated Node and/or updated Million, my Next.js app is not running with Million anymore. Running the server throws this error

```bash
Error evaluating Node.js code
TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
```

Usually, this indicates a problem with the Node version, right?

Thanks!

##### Version List
- `node v23.4.0`
- `next v15.1.0`
- `million v1.0.14`

Mac
Chrome

**Comment by elliason** [comment]
I have the same issue for:

- `node 22.12.0`
- `@million/lint 1.0.14`
- `next 15.1.3`

**Comment by martingalovic** [comment]
+1

- `node: v20.16.0`
- `"@million/lint": "^1.0.14"`
- `"million": "^3.1.11"`

Running on Macbook Pro M3 Max

**Comment by mo-mainstream** [comment]
same here. does not work with node `18.18.0` either which is required by nextjs 15. running on windows.

**Comment by TruffleClock** [comment]
+1

- `node 23.6.1, 22.13.1, 20.18.2`
- `next 15.1.6`
- `@million/lint 1.0.14`

**Comment by AnandChowdhary** [comment]
Thanks @aidenybai for your hard work, big fan of your Twitter! Just flagging for you since I'm seeing this as well with the latest deps:

- `node v22.13.1` (LTS)
- `next 15.1.6`
- `@million/lint 1.0.14`

**Comment by fedorivanenko** [comment]
+1 for 

- node 20.12.2
- next 15.1.6
- @million/lint 1.0.14
- pnpm
- vscode

Updating to next v15.2.0-canary.33 helped resolve build issues, but the VSCode extension doesn't detect the dev server

**Comment by MNBoy** [comment]
### Hi everyone 🙌🏻

## If you’re getting this error:
`TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor`

it’s because Turbopack doesn’t play well with @million/lint.

### ✅ Quick Fix: Add a Separate Dev Script

Instead of disabling Turbopack entirely, just add this to your package.json:

```
"scripts": {
  "dev": "next dev --turbopack",
  "million-dev": "next dev"
}
```

Now, run:

`npm run million-dev`

Hope this helps! 🚀

**Comment by imadghssisse** [comment]
hi, i use the last version Next 15..2.2, and i get this error
```
Error evaluating Node.js code
TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
    [at Object.<anonymous> (/Users/imad/Documents/work/mandasales/front/node_modules/.pnpm/@pnpm+npm-conf@2.3.1/node_modules/@pnpm/npm-conf/lib/defaults.js:23:19)]
    [at Module._compile (node:internal/modules/cjs/loader:1469:14)]
    [at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)]
    [at Module.load (node:internal/modules/cjs/loader:1288:32)]
    [at Module._load (node:internal/modules/cjs/loader:1104:12)]
    [at Module.require (node:internal/modules/cjs/loader:1311:19)]
    [at require (node:internal/modules/helpers:179:18)]
    [at Object.<anonymous> (/Users/imad/Documents/work/mandasales/front/node_modules/.pnpm/@pnpm+npm-conf@2.3.1/node_modules/@pnpm/npm-conf/index.js:4:19)]
    [at Module._compile (node:internal/modules/cjs/loader:1469:14)]
    [at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)]
```

any idea how i can fix this?

**Comment by MNBoy** [comment]
> hi, i use the last version Next 15..2.2, and i get this error
> 
> ```
> Error evaluating Node.js code
> TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
>     [at Object.<anonymous> (/Users/imad/Documents/work/mandasales/front/node_modules/.pnpm/@pnpm+npm-conf@2.3.1/node_modules/@pnpm/npm-conf/lib/defaults.js:23:19)]
>     [at Module._compile (node:internal/modules/cjs/loader:1469:14)]
>     [at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)]
>     [at Module.load (node:internal/modules/cjs/loader:1288:32)]
>     [at Module._load (node:internal/modules/cjs/loader:1104:12)]
>     [at Module.require (node:internal/modules/cjs/loader:1311:19)]
>     [at require (node:internal/modules/helpers:179:18)]
>     [at Object.<anonymous> (/Users/imad/Documents/work/mandasales/front/node_modules/.pnpm/@pnpm+npm-conf@2.3.1/node_modules/@pnpm/npm-conf/index.js:4:19)]
>     [at Module._compile (node:internal/modules/cjs/loader:1469:14)]
>     [at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)]
> ```
> 
> any idea how i can fix this?

https://github.com/aidenybai/million/issues/1167#issuecomment-2633321643

**Comment by timneutkens** [comment]
If everyone reporting this is using Next.js with Turbopack it's likely that https://github.com/vercel/next.js/pull/78962 will fix this issue. Let me know!

**Comment by tefkah** [comment]
@timneutkens This does seem to resolve that error in canary (after upgrading from 15.3.3), thank you! 
I'm still running into issues with making million lint work with turbopack, but it's likely separate

![Image](https://github.com/user-attachments/assets/7a92f1a1-e438-495d-bad0-82f4ea66269c)
