### ISSUE TITLE
Vite: Could not resolve "react-dom/client"

### ISSUE THREAD

**Issue by komyg** [aidenybai/million#415]
Hi,

I am trying out Million on one of my projects, but I am getting this error below:

```
✘ [ERROR] Could not resolve "react-dom/client"

    node_modules/million/dist/react.mjs:7:7:
      7 │ import 'react-dom/client';
        ╵        ~~~~~~~~~~~~~~~~~~

  You can mark the path "react-dom/client" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "react-dom/client"

    node_modules/million/dist/chunks/utils.mjs:2:27:
      2 │ import { createRoot } from 'react-dom/client';

[...]
Error: Build failed with 2 errors:
node_modules/million/dist/chunks/utils.mjs:2:27: ERROR: Could not resolve "react-dom/client"
node_modules/million/dist/react.mjs:7:7: ERROR: Could not resolve "react-dom/client"
    at failureErrorWithLog (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/felipe/Development/Plato/plato/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'node_modules/million/dist/chunks/utils.mjs',
        length: 18,
        line: 2,
        lineText: "import { createRoot } from 'react-dom/client';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "react-dom/client" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "react-dom/client"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: 'node_modules/million/dist/react.mjs',
        length: 18,
        line: 7,
        lineText: "import 'react-dom/client';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "react-dom/client" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "react-dom/client"'
    }
  ],
  warnings: []
}
```

I am using:
- Vite: 4.2.1.
- React: 17.0.2
- Node: 18.16.0

Does Million only supports React 18 or the latest version of Vite?

Thank you,
Komyg

**Comment by aidenybai** [comment]
We do support React 18, but should also support older versions as well. We assume the user has `react` and `react-dom` installed. Are they installed by your Vite project?

**Comment by komyg** [comment]
Actually, we are using React 17.

But yes, we do have `react` and `react-dom` installed, but they weren't installed by `vite`. We just used `npm install react react-dom` directly.

**Comment by aidenybai** [comment]
I think this is just a React 18 incompatibility. Although it would be quite nice to support React 17: https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

**Comment by komyg** [comment]
Ok, I'll see about upgrading our app.

Also, thank you for adding [this](https://github.com/aidenybai/million/commit/8ae5f2f7f7305f02b978f12e8d60a9e91bea32d8) warning on the documentation.
