### ISSUE TITLE
[BUG]  Taking syntax error when running the millionjs sample. 

### ISSUE THREAD

**Issue by Swindler36** [aidenybai/million#49]
My node.js code:

```js
const { m, createElement, patch } = require('million');

const app = createElement(m('div', { id: 'app' }, ['Hello World']));

console.log(app);
```
My node version is `12.16.1`.
npm is `6.13.4`.

Error:

````
...\node_modules\million\dist\million.umd.js:78
      if (props?.key) {
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Furkan\Documents\GitHub\Kapseli-UI-Framework\test.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by aidenybai** [comment]
Is this still an issue? I think you need to use a bundler

**Comment by Swindler36** [comment]
Ok. I solved this issue. I tried it on a node.js env instead of the browser. :)
