### ISSUE TITLE
Error after adding `million.vite()` - Cannot find package '@babel/plugin-syntax-typescript' imported from /home/projects/github-mcbrky-jthk8n/babel-virtual-resolve-base.js

### ISSUE THREAD

**Issue by AbhiPrasad** [aidenybai/million#532]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

MacOS

### What browser are you using?

Chrome, Firefox

### Describe the Bug

Testing with adding million to https://github.com/sldk-yuri/realworld-react-fsd

Changes made:

```diff
diff --git a/package.json b/package.json
index 688ff5c..83ee8bb 100644
--- a/package.json
+++ b/package.json
@@ -25,6 +25,7 @@
     "classnames": "^2.3.2",
     "dayjs": "^1.11.7",
     "formik": "^2.4.0",
+    "million": "^2.5.13",
     "react": "^18.2.0",
     "react-dom": "^18.2.0",
     "react-error-boundary": "^4.0.10",
diff --git a/vite.config.ts b/vite.config.ts
index c51a1bf..52346c3 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -1,5 +1,6 @@
 import path from 'path';
 import react from '@vitejs/plugin-react';
+import million from 'million/compiler';
 import unfonts from 'unplugin-fonts/vite';
 import checker from 'vite-plugin-checker';
 import eslint from 'vite-plugin-eslint';
@@ -8,6 +9,7 @@ import { defineConfig } from 'vitest/config';
 // https://vitejs.dev/config/
 export default defineConfig({
   plugins: [
+    million.vite(),
     react(),
     eslint(),
     checker({ typescript: true }),
```

```
[plugin:million] Cannot find package '@babel/plugin-syntax-typescript' imported from /home/projects/github-pjvtut/babel-virtual-resolve-base.js
/home/projects/github-pjvtut/src/app/index.tsx
    at __node_internal_ (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:233:9)
    at new NodeError (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at resolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:13:10)
    at tryImportMetaResolve (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/files/plugins.js:137:45)
    at resolveStandardizedNameForImport (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/files/plugins.js:159:19)
    at resolveStandardizedName (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/files/plugins.js:168:12)
    at loadPlugin (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/files/plugins.js:47:20)
    at createDescriptor (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at step (/home/projects/github-pjvtut/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/projects/github-pjvtut/node_modules/gensync/index.js:291:5)
    at eval (/home/projects/github-pjvtut/node_modules/gensync/index.js:44:11)
    at Function.async (/home/projects/github-pjvtut/node_modules/gensync/index.js:43:15)
    at Function.all (/home/projects/github-pjvtut/node_modules/gensync/index.js:216:13)
    at createDescriptors (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createPluginDescriptors (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at eval (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-descriptors.js:65:32)
    at Function.eval (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at step (/home/projects/github-pjvtut/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/home/projects/github-pjvtut/node_modules/gensync/index.js:291:5)
    at Function.errback (/home/projects/github-pjvtut/node_modules/gensync/index.js:113:7)
    at errback (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/gensync-utils/async.js:66:18)
    at async (/home/projects/github-pjvtut/node_modules/gensync/index.js:188:17)
    at onFirstPause (/home/projects/github-pjvtut/node_modules/gensync/index.js:216:13)
    at cachedFunction (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/caching.js:52:46)
    at mergeChainOpts (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-chain.js:350:34)
    at chainWalker (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-chain.js:317:14)
    at buildRootChain (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/config-chain.js:57:36)
    at loadPrivatePartialConfig (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/partial.js:79:62)
    at loadFullConfig (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/config/full.js:36:46)
    at transform (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/transform.js:20:45)
    at step (/home/projects/github-pjvtut/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/home/projects/github-pjvtut/node_modules/gensync/index.js:291:5)
    at eval (/home/projects/github-pjvtut/node_modules/gensync/index.js:93:9)
    at async (/home/projects/github-pjvtut/node_modules/gensync/index.js:92:14)
    at Module.transformAsync (/home/projects/github-pjvtut/node_modules/million/node_modules/@babel/core/lib/transform.js:46:77)
    at TransformContext.transform (/home/projects/github-pjvtut/node_modules/million/dist/compiler.mjs:2986:40)
    at plugin.transform (/home/projects/github-pjvtut/node_modules/unplugin/dist/index.mjs:1173:25)
    at Object.transform (/home/projects/github-pjvtut/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42971:44)
    at loadAndTransform (/home/projects/github-pjvtut/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53437:51
```

### What's the expected result?

Doesn't throw an error on build when I add the `millon.vite()`

Babel does seem like a maintenance burden - any thoughts of trying https://github.com/unjs/magicast instead for the AST parsing?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pjvtut

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Timonwa** [comment]
Hi @AbhiPrasad, you have created a pull request to fix this issue, but it created another one. So now it's seeing the imports but not exporting them?
